/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class groupnode : XdrAble {
    public name grname;
    public groups grnext;

    public groupnode() {
    }

    public groupnode(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        grname.xdrEncode(xdr);
        grnext.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        grname = new name(xdr);
        grnext = new groups(xdr);
    }

}
// End of groupnode.cs
