/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class COMMIT3resok : XdrAble {
    public wcc_data file_wcc;
    public writeverf3 verf;

    public COMMIT3resok() {
    }

    public COMMIT3resok(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        file_wcc.xdrEncode(xdr);
        verf.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        file_wcc = new wcc_data(xdr);
        verf = new writeverf3(xdr);
    }

}
// End of COMMIT3resok.cs
