/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class CREATE3args : XdrAble {
    public diropargs3 where;
    public createhow3 how;

    public CREATE3args() {
    }

    public CREATE3args(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        where.xdrEncode(xdr);
        how.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        where = new diropargs3(xdr);
        how = new createhow3(xdr);
    }

}
// End of CREATE3args.cs
