/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class LOOKUP3resok : XdrAble {
    public nfs_fh3 obj;
    public post_op_attr obj_attributes;
    public post_op_attr dir_attributes;

    public LOOKUP3resok() {
    }

    public LOOKUP3resok(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        obj.xdrEncode(xdr);
        obj_attributes.xdrEncode(xdr);
        dir_attributes.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        obj = new nfs_fh3(xdr);
        obj_attributes = new post_op_attr(xdr);
        dir_attributes = new post_op_attr(xdr);
    }

}
// End of LOOKUP3resok.cs
