/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class MKNOD3resfail : XdrAble {
    public wcc_data dir_wcc;

    public MKNOD3resfail() {
    }

    public MKNOD3resfail(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        dir_wcc.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        dir_wcc = new wcc_data(xdr);
    }

}
// End of MKNOD3resfail.cs
