/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
/**
 * Enumeration (collection of constants).
 */
public class nfsstat3 {

    public const int NFS3_OK = 0;
    public const int NFS3ERR_PERM = 1;
    public const int NFS3ERR_NOENT = 2;
    public const int NFS3ERR_IO = 5;
    public const int NFS3ERR_NXIO = 6;
    public const int NFS3ERR_ACCES = 13;
    public const int NFS3ERR_EXIST = 17;
    public const int NFS3ERR_XDEV = 18;
    public const int NFS3ERR_NODEV = 19;
    public const int NFS3ERR_NOTDIR = 20;
    public const int NFS3ERR_ISDIR = 21;
    public const int NFS3ERR_INVAL = 22;
    public const int NFS3ERR_FBIG = 27;
    public const int NFS3ERR_NOSPC = 28;
    public const int NFS3ERR_ROFS = 30;
    public const int NFS3ERR_MLINK = 31;
    public const int NFS3ERR_NAMETOOLONG = 63;
    public const int NFS3ERR_NOTEMPTY = 66;
    public const int NFS3ERR_DQUOT = 69;
    public const int NFS3ERR_STALE = 70;
    public const int NFS3ERR_REMOTE = 71;
    public const int NFS3ERR_BADHANDLE = 10001;
    public const int NFS3ERR_NOT_SYNC = 10002;
    public const int NFS3ERR_BAD_COOKIE = 10003;
    public const int NFS3ERR_NOTSUPP = 10004;
    public const int NFS3ERR_TOOSMALL = 10005;
    public const int NFS3ERR_SERVERFAULT = 10006;
    public const int NFS3ERR_BADTYPE = 10007;
    public const int NFS3ERR_JUKEBOX = 10008;

}
// End of nfsstat3.cs
