/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class READDIRPLUS3resok : XdrAble {
    public post_op_attr dir_attributes;
    public cookieverf3 cookieverf;
    public dirlistplus3 reply;

    public READDIRPLUS3resok() {
    }

    public READDIRPLUS3resok(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        dir_attributes.xdrEncode(xdr);
        cookieverf.xdrEncode(xdr);
        reply.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        dir_attributes = new post_op_attr(xdr);
        cookieverf = new cookieverf3(xdr);
        reply = new dirlistplus3(xdr);
    }

}
// End of READDIRPLUS3resok.cs
