/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class READLINK3resok : XdrAble {
    public post_op_attr symlink_attributes;
    public nfspath3 data;

    public READLINK3resok() {
    }

    public READLINK3resok(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        symlink_attributes.xdrEncode(xdr);
        data.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        symlink_attributes = new post_op_attr(xdr);
        data = new nfspath3(xdr);
    }

}
// End of READLINK3resok.cs
