/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class READLINK3resfail : XdrAble {
    public post_op_attr symlink_attributes;

    public READLINK3resfail() {
    }

    public READLINK3resfail(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        symlink_attributes.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        symlink_attributes = new post_op_attr(xdr);
    }

}
// End of READLINK3resfail.cs
