/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class RENAME3args : XdrAble {
    public diropargs3 from;
    public diropargs3 to;

    public RENAME3args() {
    }

    public RENAME3args(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        from.xdrEncode(xdr);
        to.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        from = new diropargs3(xdr);
        to = new diropargs3(xdr);
    }

}
// End of RENAME3args.cs
