/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class set_size3 : XdrAble {
    public bool set_it;
    public size3 size;

    public set_size3() {
    }

    public set_size3(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeBoolean(set_it);
        if ( set_it == true ) {
            size.xdrEncode(xdr);
        }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        set_it = xdr.xdrDecodeBoolean();
        if ( set_it == true ) {
            size = new size3(xdr);
        }
    }

}
// End of set_size3.cs
