/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class set_atime : XdrAble {
    public int set_it;
    public nfstime3 atime;

    public set_atime() {
    }

    public set_atime(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeInt(set_it);
        switch ( set_it ) {
        case time_how.SET_TO_CLIENT_TIME:
            atime.xdrEncode(xdr);
            break;
        default:
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        set_it = xdr.xdrDecodeInt();
        switch ( set_it ) {
        case time_how.SET_TO_CLIENT_TIME:
            atime = new nfstime3(xdr);
            break;
        default:
            break;
        }
    }

}
// End of set_atime.cs
