/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class SETATTR3resok : XdrAble {
    public wcc_data obj_wcc;

    public SETATTR3resok() {
    }

    public SETATTR3resok(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        obj_wcc.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        obj_wcc = new wcc_data(xdr);
    }

}
// End of SETATTR3resok.cs
