/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
/**
 * Enumeration (collection of constants).
 */
public class time_how {

    public const int DONT_CHANGE = 0;
    public const int SET_TO_SERVER_TIME = 1;
    public const int SET_TO_CLIENT_TIME = 2;

}
// End of time_how.cs
