/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class uint32 : XdrAble {

    public int value;

    public uint32() {
    }

    public uint32(int value) {
        this.value = value;
    }

    public uint32(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeInt(value);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        this.value = xdr.xdrDecodeInt();
    }

}
// End of uint32.cs
