/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class ACCESS3args : XdrAble {
    public nfs_fh3 obj;
    public uint32 access;

    public ACCESS3args() {
    }

    public ACCESS3args(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        obj.xdrEncode(xdr);
        access.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        obj = new nfs_fh3(xdr);
        access = new uint32(xdr);
    }

}
// End of ACCESS3args.cs
