/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class devicedata3 : XdrAble {
    public sattr3 dev_attributes;
    public specdata3 spec;

    public devicedata3() {
    }

    public devicedata3(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        dev_attributes.xdrEncode(xdr);
        spec.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        dev_attributes = new sattr3(xdr);
        spec = new specdata3(xdr);
    }

}
// End of devicedata3.cs
