/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class FSINFO3args : XdrAble {
    public nfs_fh3 fsroot;

    public FSINFO3args() {
    }

    public FSINFO3args(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        fsroot.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        fsroot = new nfs_fh3(xdr);
    }

}
// End of FSINFO3args.cs
