/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
/**
 * Enumeration (collection of constants).
 */
public class ftype3 {

    public const int NF3REG = 1;
    public const int NF3DIR = 2;
    public const int NF3BLK = 3;
    public const int NF3CHR = 4;
    public const int NF3LNK = 5;
    public const int NF3SOCK = 6;
    public const int NF3FIFO = 7;

}
// End of ftype3.cs
