/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class MKDIR3args : XdrAble {
    public diropargs3 where;
    public sattr3 attributes;

    public MKDIR3args() {
    }

    public MKDIR3args(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        where.xdrEncode(xdr);
        attributes.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        where = new diropargs3(xdr);
        attributes = new sattr3(xdr);
    }

}
// End of MKDIR3args.cs
