/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class MKNOD3args : XdrAble {
    public diropargs3 where;
    public mknoddata3 what;

    public MKNOD3args() {
    }

    public MKNOD3args(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        where.xdrEncode(xdr);
        what.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        where = new diropargs3(xdr);
        what = new mknoddata3(xdr);
    }

}
// End of MKNOD3args.cs
