/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
/**
 * A collection of constants used by the "NFSv3Protocol" ONC/RPC program.
 */
public class NFSv3Protocol {
    public const int ACCESS3_READ = 0x0001;
    public const int NFSPROC3_READ_3 = 6;
    public const int NFSPROC3_GETATTR_3 = 1;
    public const int FSF3_SYMLINK = 0x0002;
    public const int NFSPROC3_LOOKUP_3 = 3;
    public const int NFS3_COOKIEVERFSIZE = 8;
    public const int FSF3_HOMOGENEOUS = 0x0008;
    public const int NFS_V3 = 3;
    public const int ACCESS3_EXTEND = 0x0008;
    public const int NFSPROC3_MKNOD_3 = 11;
    public const int NFSPROC3_NULL_3 = 0;
    public const int NFSPROC3_READDIRPLUS_3 = 17;
    public const int NFSPROC3_RMDIR_3 = 13;
    public const int NFSPROC3_READLINK_3 = 5;
    public const int NFS3_CREATEVERFSIZE = 8;
    public const int FSF3_CANSETTIME = 0x0010;
    public const int NFSPROC3_SETATTR_3 = 2;
    public const int NFSPROC3_MKDIR_3 = 9;
    public const int NFSPROC3_COMMIT_3 = 21;
    public const int NFSPROC3_RENAME_3 = 14;
    public const int NFSPROC3_CREATE_3 = 8;
    public const int NFSPROC3_READDIR_3 = 16;
    public const int NFSPROC3_REMOVE_3 = 12;
    public const int FSF3_LINK = 0x0001;
    public const int ACCESS3_LOOKUP = 0x0002;
    public const int NFSPROC3_LINK_3 = 15;
    public const int ACCESS3_DELETE = 0x0010;
    public const int NFSPROC3_ACCESS_3 = 4;
    public const int ACCESS3_EXECUTE = 0x0020;
    public const int NFSPROC3_PATHCONF_3 = 20;
    public const int NFS_PROGRAM = 100003;
    public const int NFSPROC3_FSINFO_3 = 19;
    public const int NFSPROC3_WRITE_3 = 7;
    public const int NFS3_WRITEVERFSIZE = 8;
    public const int ACCESS3_MODIFY = 0x0004;
    public const int NFS3_FHSIZE = 64;
    public const int NFSPROC3_FSSTAT_3 = 18;
    public const int NFSPROC3_SYMLINK_3 = 10;
}
// End of NFSv3Protocol.cs
