/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class PATHCONF3resok : XdrAble {
    public post_op_attr obj_attributes;
    public uint32 linkmax;
    public uint32 name_max;
    public bool no_trunc;
    public bool chown_restricted;
    public bool case_insensitive;
    public bool case_preserving;

    public PATHCONF3resok() {
    }

    public PATHCONF3resok(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        obj_attributes.xdrEncode(xdr);
        linkmax.xdrEncode(xdr);
        name_max.xdrEncode(xdr);
        xdr.xdrEncodeBoolean(no_trunc);
        xdr.xdrEncodeBoolean(chown_restricted);
        xdr.xdrEncodeBoolean(case_insensitive);
        xdr.xdrEncodeBoolean(case_preserving);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        obj_attributes = new post_op_attr(xdr);
        linkmax = new uint32(xdr);
        name_max = new uint32(xdr);
        no_trunc = xdr.xdrDecodeBoolean();
        chown_restricted = xdr.xdrDecodeBoolean();
        case_insensitive = xdr.xdrDecodeBoolean();
        case_preserving = xdr.xdrDecodeBoolean();
    }

}
// End of PATHCONF3resok.cs
