/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class post_op_fh3 : XdrAble {
    public bool handle_follows;
    public nfs_fh3 handle;

    public post_op_fh3() {
    }

    public post_op_fh3(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeBoolean(handle_follows);
        if ( handle_follows == true ) {
            handle.xdrEncode(xdr);
        }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        handle_follows = xdr.xdrDecodeBoolean();
        if ( handle_follows == true ) {
            handle = new nfs_fh3(xdr);
        }
    }

}
// End of post_op_fh3.cs
