/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class pre_op_attr : XdrAble {
    public bool attributes_follow;
    public wcc_attr attributes;

    public pre_op_attr() {
    }

    public pre_op_attr(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeBoolean(attributes_follow);
        if ( attributes_follow == true ) {
            attributes.xdrEncode(xdr);
        }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        attributes_follow = xdr.xdrDecodeBoolean();
        if ( attributes_follow == true ) {
            attributes = new wcc_attr(xdr);
        }
    }

}
// End of pre_op_attr.cs
