/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class REMOVE3args : XdrAble {
    public diropargs3 obj;

    public REMOVE3args() {
    }

    public REMOVE3args(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        obj.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        obj = new diropargs3(xdr);
    }

}
// End of REMOVE3args.cs
