/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class RMDIR3args : XdrAble {
    public diropargs3 obj;

    public RMDIR3args() {
    }

    public RMDIR3args(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        obj.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        obj = new diropargs3(xdr);
    }

}
// End of RMDIR3args.cs
