/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class sattr3 : XdrAble {
    public set_mode3 mode;
    public set_uid3 uid;
    public set_gid3 gid;
    public set_size3 size;
    public set_atime atime;
    public set_mtime mtime;

    public sattr3() {
    }

    public sattr3(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        mode.xdrEncode(xdr);
        uid.xdrEncode(xdr);
        gid.xdrEncode(xdr);
        size.xdrEncode(xdr);
        atime.xdrEncode(xdr);
        mtime.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        mode = new set_mode3(xdr);
        uid = new set_uid3(xdr);
        gid = new set_gid3(xdr);
        size = new set_size3(xdr);
        atime = new set_atime(xdr);
        mtime = new set_mtime(xdr);
    }

}
// End of sattr3.cs
