/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class set_mode3 : XdrAble {
    public bool set_it;
    public mode3 mode;

    public set_mode3() {
    }

    public set_mode3(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeBoolean(set_it);
        if ( set_it == true ) {
            mode.xdrEncode(xdr);
        }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        set_it = xdr.xdrDecodeBoolean();
        if ( set_it == true ) {
            mode = new mode3(xdr);
        }
    }

}
// End of set_mode3.cs
