/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class SETATTR3args : XdrAble {
    public nfs_fh3 obj;
    public sattr3 new_attributes;
    public sattrguard3 guard;

    public SETATTR3args() {
    }

    public SETATTR3args(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        obj.xdrEncode(xdr);
        new_attributes.xdrEncode(xdr);
        guard.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        obj = new nfs_fh3(xdr);
        new_attributes = new sattr3(xdr);
        guard = new sattrguard3(xdr);
    }

}
// End of SETATTR3args.cs
