/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
/**
 * Enumeration (collection of constants).
 */
public class stable_how {

    public const int UNSTABLE = 0;
    public const int DATA_SYNC = 1;
    public const int FILE_SYNC = 2;

}
// End of stable_how.cs
