/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class SYMLINK3args : XdrAble {
    public diropargs3 where;
    public symlinkdata3 symlink;

    public SYMLINK3args() {
    }

    public SYMLINK3args(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        where.xdrEncode(xdr);
        symlink.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        where = new diropargs3(xdr);
        symlink = new symlinkdata3(xdr);
    }

}
// End of SYMLINK3args.cs
