/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class wcc_attr : XdrAble {
    public size3 size;
    public nfstime3 mtime;
    public nfstime3 ctime;

    public wcc_attr() {
    }

    public wcc_attr(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        size.xdrEncode(xdr);
        mtime.xdrEncode(xdr);
        ctime.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        size = new size3(xdr);
        mtime = new nfstime3(xdr);
        ctime = new nfstime3(xdr);
    }

}
// End of wcc_attr.cs
