/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
/**
 * Enumeration (collection of constants).
 */
public class createmode3 {

    public const int UNCHECKED = 0;
    public const int GUARDED = 1;
    public const int EXCLUSIVE = 2;

}
// End of createmode3.cs
