/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class diropargs3 : XdrAble {
    public nfs_fh3 dir;
    public filename3 name;

    public diropargs3() {
    }

    public diropargs3(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        dir.xdrEncode(xdr);
        name.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        dir = new nfs_fh3(xdr);
        name = new filename3(xdr);
    }

}
// End of diropargs3.cs
