/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class entryplus3 : XdrAble {
    public fileid3 fileid;
    public filename3 name;
    public cookie3 cookie;
    public post_op_attr name_attributes;
    public post_op_fh3 name_handle;
    public entryplus3 nextentry;

    public entryplus3() {
    }

    public entryplus3(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        entryplus3 _this = this;
        do {
            _this.fileid.xdrEncode(xdr);
            _this.name.xdrEncode(xdr);
            _this.cookie.xdrEncode(xdr);
            _this.name_attributes.xdrEncode(xdr);
            _this.name_handle.xdrEncode(xdr);
            _this = _this.nextentry;
            xdr.xdrEncodeBoolean(_this != null);
        } while ( _this != null );
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        entryplus3 _this = this;
        entryplus3 _next;
        do {
            _this.fileid = new fileid3(xdr);
            _this.name = new filename3(xdr);
            _this.cookie = new cookie3(xdr);
            _this.name_attributes = new post_op_attr(xdr);
            _this.name_handle = new post_op_fh3(xdr);
            _next = xdr.xdrDecodeBoolean() ? new entryplus3() : null;
            _this.nextentry = _next;
            _this = _next;
        } while ( _this != null );
    }

}
// End of entryplus3.cs
