/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class FSINFO3resok : XdrAble {
    public post_op_attr obj_attributes;
    public uint32 rtmax;
    public uint32 rtpref;
    public uint32 rtmult;
    public uint32 wtmax;
    public uint32 wtpref;
    public uint32 wtmult;
    public uint32 dtpref;
    public size3 maxfilesize;
    public nfstime3 time_delta;
    public uint32 properties;

    public FSINFO3resok() {
    }

    public FSINFO3resok(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        obj_attributes.xdrEncode(xdr);
        rtmax.xdrEncode(xdr);
        rtpref.xdrEncode(xdr);
        rtmult.xdrEncode(xdr);
        wtmax.xdrEncode(xdr);
        wtpref.xdrEncode(xdr);
        wtmult.xdrEncode(xdr);
        dtpref.xdrEncode(xdr);
        maxfilesize.xdrEncode(xdr);
        time_delta.xdrEncode(xdr);
        properties.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        obj_attributes = new post_op_attr(xdr);
        rtmax = new uint32(xdr);
        rtpref = new uint32(xdr);
        rtmult = new uint32(xdr);
        wtmax = new uint32(xdr);
        wtpref = new uint32(xdr);
        wtmult = new uint32(xdr);
        dtpref = new uint32(xdr);
        maxfilesize = new size3(xdr);
        time_delta = new nfstime3(xdr);
        properties = new uint32(xdr);
    }

}
// End of FSINFO3resok.cs
