/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class LOOKUP3args : XdrAble {
    public diropargs3 what;

    public LOOKUP3args() {
    }

    public LOOKUP3args(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        what.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        what = new diropargs3(xdr);
    }

}
// End of LOOKUP3args.cs
