/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class mknoddata3 : XdrAble {
    public int type;
    public devicedata3 device_chr;
    public devicedata3 device_blk;
    public sattr3 pipe_attributes_sock;
    public sattr3 pipe_attributes_fifo;

    public mknoddata3() {
    }

    public mknoddata3(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeInt(type);
        switch ( type ) {
        case ftype3.NF3CHR:
            device_chr.xdrEncode(xdr);
            break;
        case ftype3.NF3BLK:
            device_blk.xdrEncode(xdr);
            break;
        case ftype3.NF3SOCK:
            pipe_attributes_sock.xdrEncode(xdr);
            break;
        case ftype3.NF3FIFO:
            pipe_attributes_fifo.xdrEncode(xdr);
            break;
        default:
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        type = xdr.xdrDecodeInt();
        switch ( type ) {
        case ftype3.NF3CHR:
            device_chr = new devicedata3(xdr);
            break;
        case ftype3.NF3BLK:
            device_blk = new devicedata3(xdr);
            break;
        case ftype3.NF3SOCK:
            pipe_attributes_sock = new sattr3(xdr);
            break;
        case ftype3.NF3FIFO:
            pipe_attributes_fifo = new sattr3(xdr);
            break;
        default:
            break;
        }
    }

}
// End of mknoddata3.cs
