/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class READ3resok : XdrAble {
    public post_op_attr file_attributes;
    public count3 count;
    public bool eof;
    public byte [] data;

    public READ3resok() {
    }

    public READ3resok(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        file_attributes.xdrEncode(xdr);
        count.xdrEncode(xdr);
        xdr.xdrEncodeBoolean(eof);
        xdr.xdrEncodeDynamicOpaque(data);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        file_attributes = new post_op_attr(xdr);
        count = new count3(xdr);
        eof = xdr.xdrDecodeBoolean();
        data = xdr.xdrDecodeDynamicOpaque();
    }

}
// End of READ3resok.cs
