/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class READDIRPLUS3resfail : XdrAble {
    public post_op_attr dir_attributes;

    public READDIRPLUS3resfail() {
    }

    public READDIRPLUS3resfail(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        dir_attributes.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        dir_attributes = new post_op_attr(xdr);
    }

}
// End of READDIRPLUS3resfail.cs
