/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class READDIR3args : XdrAble {
    public nfs_fh3 dir;
    public cookie3 cookie;
    public cookieverf3 cookieverf;
    public count3 count;

    public READDIR3args() {
    }

    public READDIR3args(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        dir.xdrEncode(xdr);
        cookie.xdrEncode(xdr);
        cookieverf.xdrEncode(xdr);
        count.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        dir = new nfs_fh3(xdr);
        cookie = new cookie3(xdr);
        cookieverf = new cookieverf3(xdr);
        count = new count3(xdr);
    }

}
// End of READDIR3args.cs
