/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class RENAME3resfail : XdrAble {
    public wcc_data fromdir_wcc;
    public wcc_data todir_wcc;

    public RENAME3resfail() {
    }

    public RENAME3resfail(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        fromdir_wcc.xdrEncode(xdr);
        todir_wcc.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        fromdir_wcc = new wcc_data(xdr);
        todir_wcc = new wcc_data(xdr);
    }

}
// End of RENAME3resfail.cs
