/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class specdata3 : XdrAble {
    public uint32 specdata1;
    public uint32 specdata2;

    public specdata3() {
    }

    public specdata3(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        specdata1.xdrEncode(xdr);
        specdata2.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        specdata1 = new uint32(xdr);
        specdata2 = new uint32(xdr);
    }

}
// End of specdata3.cs
