/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class symlinkdata3 : XdrAble {
    public sattr3 symlink_attributes;
    public nfspath3 symlink_data;

    public symlinkdata3() {
    }

    public symlinkdata3(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        symlink_attributes.xdrEncode(xdr);
        symlink_data.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        symlink_attributes = new sattr3(xdr);
        symlink_data = new nfspath3(xdr);
    }

}
// End of symlinkdata3.cs
