/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class WRITE3resfail : XdrAble {
    public wcc_data file_wcc;

    public WRITE3resfail() {
    }

    public WRITE3resfail(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        file_wcc.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        file_wcc = new wcc_data(xdr);
    }

}
// End of WRITE3resfail.cs
