/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class WRITE3resok : XdrAble {
    public wcc_data file_wcc;
    public count3 count;
    public int committed;
    public writeverf3 verf;

    public WRITE3resok() {
    }

    public WRITE3resok(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        file_wcc.xdrEncode(xdr);
        count.xdrEncode(xdr);
        xdr.xdrEncodeInt(committed);
        verf.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        file_wcc = new wcc_data(xdr);
        count = new count3(xdr);
        committed = xdr.xdrDecodeInt();
        verf = new writeverf3(xdr);
    }

}
// End of WRITE3resok.cs
