/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
/**
 * Enumeration (collection of constants).
 */
public class ftype {

    public const int NFNON = 0;
    public const int NFREG = 1;
    public const int NFDIR = 2;
    public const int NFBLK = 3;
    public const int NFCHR = 4;
    public const int NFLNK = 5;

}
// End of ftype.cs
