/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class info : XdrAble {
    public int tsize;
    public int bsize;
    public int blocks;
    public int bfree;
    public int bavail;

    public info() {
    }

    public info(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeInt(tsize);
        xdr.xdrEncodeInt(bsize);
        xdr.xdrEncodeInt(blocks);
        xdr.xdrEncodeInt(bfree);
        xdr.xdrEncodeInt(bavail);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        tsize = xdr.xdrDecodeInt();
        bsize = xdr.xdrDecodeInt();
        blocks = xdr.xdrDecodeInt();
        bfree = xdr.xdrDecodeInt();
        bavail = xdr.xdrDecodeInt();
    }

}
// End of info.cs
