/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class linkargs : XdrAble {
    public nfshandle from;
    public diropargs to;

    public linkargs() {
    }

    public linkargs(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        from.xdrEncode(xdr);
        to.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        from = new nfshandle(xdr);
        to = new diropargs(xdr);
    }

}
// End of linkargs.cs
