/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class nfshandle : XdrAble {

    public byte [] value;

    public nfshandle() {
    }

    public nfshandle(byte [] value) {
        this.value = value;
    }

    public nfshandle(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeOpaque(value, NFSv2Protocol.FHSIZE);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        value = xdr.xdrDecodeOpaque(NFSv2Protocol.FHSIZE);
    }

}
// End of nfshandle.cs
