/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
/**
 * Enumeration (collection of constants).
 */
public class nfsstat {

    public const int NFS_OK = 0;
    public const int NFSERR_PERM = 1;
    public const int NFSERR_NOENT = 2;
    public const int NFSERR_IO = 5;
    public const int NFSERR_NXIO = 6;
    public const int NFSERR_ACCES = 13;
    public const int NFSERR_EXIST = 17;
    public const int NFSERR_NODEV = 19;
    public const int NFSERR_NOTDIR = 20;
    public const int NFSERR_ISDIR = 21;
    public const int NFSERR_FBIG = 27;
    public const int NFSERR_NOSPC = 28;
    public const int NFSERR_ROFS = 30;
    public const int NFSERR_NAMETOOLONG = 63;
    public const int NFSERR_NOTEMPTY = 66;
    public const int NFSERR_DQUOT = 69;
    public const int NFSERR_STALE = 70;
    public const int NFSERR_WFLUSH = 99;

}
// End of nfsstat.cs
