/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class readdirargs : XdrAble {
    public nfshandle dir;
    public nfscookie cookie;
    public int count;

    public readdirargs() {
    }

    public readdirargs(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        dir.xdrEncode(xdr);
        cookie.xdrEncode(xdr);
        xdr.xdrEncodeInt(count);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        dir = new nfshandle(xdr);
        cookie = new nfscookie(xdr);
        count = xdr.xdrDecodeInt();
    }

}
// End of readdirargs.cs
