/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class readresok : XdrAble {
    public fattr attributes;
    public byte [] data;

    public readresok() {
    }

    public readresok(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        attributes.xdrEncode(xdr);
        xdr.xdrEncodeDynamicOpaque(data);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        attributes = new fattr(xdr);
        data = xdr.xdrDecodeDynamicOpaque();
    }

}
// End of readresok.cs
