/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class exportnode3 : XdrAble {
    public dirpath3 ex_dir;
    public groups3 ex_groups;
    public exports3 ex_next;

    public exportnode3() {
    }

    public exportnode3(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        ex_dir.xdrEncode(xdr);
        ex_groups.xdrEncode(xdr);
        ex_next.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        ex_dir = new dirpath3(xdr);
        ex_groups = new groups3(xdr);
        ex_next = new exports3(xdr);
    }

}
// End of exportnode3.cs
