/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class groupnode3 : XdrAble {
    public name3 gr_name;
    public groups3 gr_next;

    public groupnode3() {
    }

    public groupnode3(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        gr_name.xdrEncode(xdr);
        gr_next.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        gr_name = new name3(xdr);
        gr_next = new groups3(xdr);
    }

}
// End of groupnode3.cs
