/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class groups3 : XdrAble {

    public groupnode3 value;

    public groups3() {
    }

    public groups3(groupnode3 value) {
        this.value = value;
    }

    public groups3(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        if ( value != null ) { xdr.xdrEncodeBoolean(true); value.xdrEncode(xdr); } else { xdr.xdrEncodeBoolean(false); };
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        value = xdr.xdrDecodeBoolean() ? new groupnode3(xdr) : null;
    }

}
// End of groups3.cs
