/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class mountres3 : XdrAble {
    public int fhs_status;
    public mountres3_ok mountinfo;

    public mountres3() {
    }

    public mountres3(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeInt(fhs_status);
        switch ( fhs_status ) {
        case mountstat3.MNT3_OK:
            mountinfo.xdrEncode(xdr);
            break;
        default:
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        fhs_status = xdr.xdrDecodeInt();
        switch ( fhs_status ) {
        case mountstat3.MNT3_OK:
            mountinfo = new mountres3_ok(xdr);
            break;
        default:
            break;
        }
    }

}
// End of mountres3.cs
