/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
/**
 * A collection of constants used by the "NFSv3MountProtocol" ONC/RPC program.
 */
public class NFSv3MountProtocol {
    public const int MOUNTPROC3_UMNTALL_3 = 4;
    public const int MNTPATHLEN = 1024;
    public const int MOUNT_PROGRAM = 100005;
    public const int MOUNT_V3 = 3;
    public const int MOUNTPROC3_NULL_3 = 0;
    public const int MOUNTPROC3_UMNT_3 = 3;
    public const int MOUNTPROC3_DUMP_3 = 2;
    public const int MOUNTPROC3_MNT_3 = 1;
    public const int MOUNTPROC3_EXPORT_3 = 5;
    public const int FHSIZE3 = 64;
    public const int MNTNAMLEN = 255;
}
// End of NFSv3MountProtocol.cs
