/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class diropargs : XdrAble {
    public nfshandle dir;
    public filename name;

    public diropargs() {
    }

    public diropargs(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        dir.xdrEncode(xdr);
        name.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        dir = new nfshandle(xdr);
        name = new filename(xdr);
    }

}
// End of diropargs.cs
