/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class nfstimeval : XdrAble {
    public int seconds;
    public int useconds;

    public nfstimeval() {
    }

    public nfstimeval(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        xdr.xdrEncodeInt(seconds);
        xdr.xdrEncodeInt(useconds);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        seconds = xdr.xdrDecodeInt();
        useconds = xdr.xdrDecodeInt();
    }

}
// End of nfstimeval.cs
