/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class writeargs : XdrAble {
    public nfshandle file;
    public int beginoffset;
    public int offset;
    public int totalcount;
    public byte [] data;

    public writeargs() {
    }

    public writeargs(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        file.xdrEncode(xdr);
        xdr.xdrEncodeInt(beginoffset);
        xdr.xdrEncodeInt(offset);
        xdr.xdrEncodeInt(totalcount);
        xdr.xdrEncodeDynamicOpaque(data);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        file = new nfshandle(xdr);
        beginoffset = xdr.xdrDecodeInt();
        offset = xdr.xdrDecodeInt();
        totalcount = xdr.xdrDecodeInt();
        data = xdr.xdrDecodeDynamicOpaque();
    }

}
// End of writeargs.cs
