/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class exportnode : XdrAble {
    public dirpath filesys;
    public groups exgroups;
    public exports next;

    public exportnode() {
    }

    public exportnode(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        filesys.xdrEncode(xdr);
        exgroups.xdrEncode(xdr);
        next.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        filesys = new dirpath(xdr);
        exgroups = new groups(xdr);
        next = new exports(xdr);
    }

}
// End of exportnode.cs
