/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class mountbody : XdrAble {
    public name hostname;
    public dirpath directory;
    public mountlist nextentry;

    public mountbody() {
    }

    public mountbody(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        hostname.xdrEncode(xdr);
        directory.xdrEncode(xdr);
        nextentry.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        hostname = new name(xdr);
        directory = new dirpath(xdr);
        nextentry = new mountlist(xdr);
    }

}
// End of mountbody.cs
