/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
/**
 * A collection of constants used by the "NFSv2MountProtocol" ONC/RPC program.
 */
public class NFSv2MountProtocol {
    public const int MOUNTPROC_NULL_1 = 0;
    public const int MNTPATHLEN = 1024;
    public const int MOUNTPROC_UMNTALL_1 = 4;
    public const int MOUNTPROC_MNT_1 = 1;
    public const int MOUNTPROC_UMNT_1 = 3;
    public const int MNTNAMLEN = 255;
    public const int FHSIZE = 32;
    public const int MOUNTPROC_EXPORT_1 = 5;
    public const int MOUNTPROC_DUMP_1 = 2;
    public const int MOUNTPROG = 100005;
    public const int MOUNTVERS = 1;
}
// End of NFSv2MountProtocol.cs
