/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
/**
 * Enumeration (collection of constants).
 */
public class mountstat3 {

    public const int MNT3_OK = 0;
    public const int MNT3ERR_PERM = 1;
    public const int MNT3ERR_NOENT = 2;
    public const int MNT3ERR_IO = 5;
    public const int MNT3ERR_ACCES = 13;
    public const int MNT3ERR_NOTDIR = 20;
    public const int MNT3ERR_INVAL = 22;
    public const int MNT3ERR_NAMETOOLONG = 63;
    public const int MNT3ERR_NOTSUPP = 10004;
    public const int MNT3ERR_SERVERFAULT = 10006;

}
// End of mountstat3.cs
