/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class mountbody3 : XdrAble {
    public name3 ml_hostname;
    public dirpath3 ml_directory;
    public mountlist3 ml_next;

    public mountbody3() {
    }

    public mountbody3(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        ml_hostname.xdrEncode(xdr);
        ml_directory.xdrEncode(xdr);
        ml_next.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        ml_hostname = new name3(xdr);
        ml_directory = new dirpath3(xdr);
        ml_next = new mountlist3(xdr);
    }

}
// End of mountbody3.cs
