/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class mountres3_ok : XdrAble {
    public fhandle3 fhandle;
    public int [] auth_flavors;

    public mountres3_ok() {
    }

    public mountres3_ok(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        fhandle.xdrEncode(xdr);
        xdr.xdrEncodeIntVector(auth_flavors);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        fhandle = new fhandle3(xdr);
        auth_flavors = xdr.xdrDecodeIntVector();
    }

}
// End of mountres3_ok.cs
