/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class mountlist : XdrAble {

    public mountbody value;

    public mountlist() {
    }

    public mountlist(mountbody value) {
        this.value = value;
    }

    public mountlist(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        if ( value != null ) { xdr.xdrEncodeBoolean(true); value.xdrEncode(xdr); } else { xdr.xdrEncodeBoolean(false); };
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        value = xdr.xdrDecodeBoolean() ? new mountbody(xdr) : null;
    }

}
// End of mountlist.cs
