/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
/**
 * A collection of constants used by the "NFSv2Protocol" ONC/RPC program.
 */
public class NFSv2Protocol {
    public const int NFSPROC_ROOT_2 = 3;
    public const int MAXNAMLEN = 255;
    public const int NFSPROC_READLINK_2 = 5;
    public const int MAXDATA = 8192;
    public const int NFSPROC_GETATTR_2 = 1;
    public const int NFSPROC_LOOKUP_2 = 4;
    public const int NFS_PROGRAM = 100003;
    public const int COOKIESIZE = 4;
    public const int NFSPROC_READ_2 = 6;
    public const int NFSPROC_MKDIR_2 = 14;
    public const int NFS_VERSION = 2;
    public const int NFSPROC_REMOVE_2 = 10;
    public const int NFSPROC_READDIR_2 = 16;
    public const int NFSPROC_SYMLINK_2 = 13;
    public const int MAXPATHLEN = 1024;
    public const int NFSPROC_RMDIR_2 = 15;
    public const int NFSPROC_SETATTR_2 = 2;
    public const int NFSPROC_LINK_2 = 12;
    public const int NFSPROC_NULL_2 = 0;
    public const int NFSPROC_STATFS_2 = 17;
    public const int FHSIZE = 32;
    public const int NFSPROC_RENAME_2 = 11;
    public const int NFSPROC_CREATE_2 = 9;
    public const int NFSPROC_WRITE_2 = 8;
    public const int NFSPROC_WRITECACHE_2 = 7;
}
// End of NFSv2Protocol.cs
