/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

public class symlinkargs : XdrAble {
    public diropargs from;
    public path to;
    public sattr attributes;

    public symlinkargs() {
    }

    public symlinkargs(XdrDecodingStream xdr) {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr) {
        from.xdrEncode(xdr);
        to.xdrEncode(xdr);
        attributes.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr) {
        from = new diropargs(xdr);
        to = new path(xdr);
        attributes = new sattr(xdr);
    }

}
// End of symlinkargs.cs
