/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */
using org.acplt.oncrpc;

namespace NFSLibrary.Protocols.Commons
{
    public class NFSPermission
    {
        private byte _user;
        private byte _group;
        private byte _other;

        public NFSPermission()
        { }

        public NFSPermission(byte UserAccess, byte GroupAccess, byte OtherAccess)
        {
            this._user = UserAccess;
            this._group = GroupAccess;
            this._other = OtherAccess;
        }

        public byte UserAccess
        {
            get
            { return this._user; }
            set
            { this._user = value; }
        }

        public byte GroupAccess
        {
            get
            { return this._group; }
            set
            { this._group = value; }
        }

        public byte OtherAccess
        {
            get
            { return this._other; }
            set
            { this._other = value; }
        }

        public int Mode
        {
            get
            {
                /* Calculate Permission */
                return
                    (((int)this._user) << 6) | (((int)this._group) << 3) | ((int)this._other);
                /*  ---  */
            }
            set
            {
                int tUser = value, tGroup = value, tOther = value;

                this._user = (byte)((tUser >> 6) & 0x7);
                this._group = (byte)((tGroup >> 3) & 0x7);
                this._other = (byte)(tOther & 0x7);
            }
        }
    }
}